### ISSUE TITLE
Camera data for battles

### ISSUE THREAD

**Issue by dangarfield** [petfriendamy/ff7-scarlet#11]
Hi,

I've noticed that in scene.bin editing, whilst most battles only have 3 non-FFFF camera placements, there are a number of battles that have 4 and in fact, the fourth is used as the main idle camera. (scene.bin has 4 groups of 3 cameras). eg:
- Scene 24: Formation: 99 - 2x Spencer, 1x Chocobo

Also, does it not makes sense to display as signed integers? They positions on the camera on the battle scene around a central 0,0,0 point, so signed makes sense.

Also, the direction is not really an 'angle' but a look at vector.

Thanks

**Comment by petfriendamy** [comment]
Thanks for the info! I've made the suggested changes, and they should be available now in the latest canary.

However, I checked the formation you mentioned and it seems like the fourth camera is still all FFFF, so I'm a little confused. Did I misunderstand something?

**Comment by dangarfield** [comment]
I have to apologise. I made a parsing mistake. You are 100% correct.
There are only 3 cameras per formation per scene as you have absolutely correctly stated and already implemented. Sorry for the confusion! The 4th is not the idle camera as I mentioned, it's always the 1st unless the camera scripts apply. Apologies again!
