### ISSUE TITLE
Not auto detecting kernel / scene / kernel2 with 1998 release

### ISSUE THREAD

**Issue by DLPB2** [petfriendamy/ff7-scarlet#3]
probably Scarlet is checking only for Steam structure. 

When prompted to auto find the rest from ff7.exe, it fails on 1998 version.

1998 release has 

Data\kernel\kernel.bin
Data\kernel\kernel2.bin
Data\kernel\window.bin
Data\battle\scene.bin

**Comment by petfriendamy** [comment]
Should be fixed in the canary, let me know if it works?
https://github.com/petfriendamy/ff7-scarlet/releases/tag/canary

**Comment by DLPB2** [comment]
> Should be fixed in the canary, let me know if it works? https://github.com/petfriendamy/ff7-scarlet/releases/tag/canary

I've tested and it's fixed :)

**Comment by petfriendamy** [comment]
Awesome, thanks!
